echo "  connect to gitlab gui http://localhost:$GITLAB_PORT_RAILS"
echo "  connect to gitlab ssh http://localhost:$GITLAB_PORT_SSH"
echo "  connect to gitlab registry http://localhost:$GITLAB_PORT_REGISTRY"
echo "  connect to gitlab pages http://localhost:$GITLAB_PORT_PAGES"
echo ""
echo "  connect to gitlab using docker exec -it $GITLAB_NAME /bin/bash"
echo "  check gitlab logs using docker logs -f $GITLAB_NAME"
echo "  warning !!! give it some time to start, check logs"
