
# gitlab
GITLAB_NAME=gitlab
GITLAB_PORT_RAILS=55010
GITLAB_PORT_SSH=55011
GITLAB_PORT_REGISTRY=55012
GITLAB_PORT_PAGES=55013
GITLAB_IMAG=gitlab/gitlab-ee
GITLAB_VERS=latest
GITLAB_DATA=GITLAB_data
GITLAB_CONF=GITLAB_conf
GITLAB_SECR=GITLAB_secr
GITLAB_ADMINUSER=root
GITLAB_ADMINPASS=root1337
