docker volume create $GITLABAIGATEWAY_DATA
docker volume create $GITLABAIGATEWAY_CONF

docker run -d\
 -p $GITLABAIGATEWAY_PORT:5052\
 -p $GITLABAIGATEWAY_METRICS_PORT:8082\
 --name $GITLABAIGATEWAY_NAME\
 --network=devenvnet\
 --restart=always\
 -e AIGW_GITLAB_URL=$GITLABAIGATEWAY_GITLABURL\
 -e AIGW_GITLAB_API_URL=$GITLABAIGATEWAY_GITLABAPIURL\
 $GITLABAIGATEWAY_IMAG:$GITLABAIGATEWAY_VERS