
# mongodb 5
GITLABAIGATEWAY_NAME=gitlabaigateway
GITLABAIGATEWAY_PORT=55014
GITLABAIGATEWAY_METRICS_PORT=55015
GITLABAIGATEWAY_IMAG=registry.gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/model-gateway
GITLABAIGATEWAY_VERS=self-hosted-v18.0.1-ee
GITLABAIGATEWAY_DATA=gitlabaigateway_data
GITLABAIGATEWAY_CONF=gitlabaigateway_conf
GITLABAIGATEWAY_ADMINUSER=admin
GITLABAIGATEWAY_ADMINPASS=admin
GITLABAIGATEWAY_GITLABURL=http://localhost:55010
GITLABAIGATEWAY_GITLABAPIURL=http://localhost:55010/api/v4/