docker volume create $GITLAB18AIGATEWAY_DATA
docker volume create $GITLAB18AIGATEWAY_CONF

docker run -d\
 -p $GITLAB18AIGATEWAY_PORT:5052\
 -p $GITLAB18AIGATEWAY_METRICS_PORT:8082\
 --name $GITLAB18AIGATEWAY_NAME\
 --network=devenvnet\
 --restart=always\
 -e AIGW_GITLAB_URL=$GITLAB18AIGATEWAY_GITLABURL\
 -e AIGW_GITLAB_API_URL=$GITLAB18AIGATEWAY_GITLABAPIURL\
 $GITLAB18AIGATEWAY_IMAG:$GITLAB18AIGATEWAY_VERS