
# mongodb 5
MINIO_NAME=minio
MINIO_PORT_API=55007
MINIO_PORT_GUI=55008
MINIO_IMAG=quay.io/minio/minio
MINIO_VERS=latest
MINIO_DATA=MINIO_data
MINIO_CONF=MINIO_conf
MINIO_ADMINUSER=admin
MINIO_ADMINPASS=adminminio
