agent:
  listen:
    address: localhost:8150
    network: tcp
    websocket: true
  configuration:
    poll_period: 300s
  kubernetes_api:
    listen:
      address: localhost:8154
    url_path_prefix: /
    websocket_token_secret_file: /var/opt/gitlab/gitlab-kas/websocket_token_secret_file
  info_cache_ttl: 300s
  info_cache_error_ttl: 60s
gitlab:
  address: http://2a820b749a5e
  external_url: http://2a820b749a5e
  authentication_secret_file: /var/opt/gitlab/gitlab-kas/authentication_secret_file
observability:
  listen:
    address: localhost:8151
    network: tcp
  usage_reporting_period: 60s
  logging:
    level: info
    grpc_level: error
redis:
  network: unix
  tls:
    enabled: false
  server:
    address: '/var/opt/gitlab/redis/redis.socket'
api:
  listen:
    network: tcp
    address: localhost:8153
    authentication_secret_file: /var/opt/gitlab/gitlab-kas/authentication_secret_file
private_api:
  listen:
    network: tcp
    address: localhost:8155
    authentication_secret_file: /var/opt/gitlab/gitlab-kas/private_api_authentication_secret_file
config:
